
# Efinity Option Register
# Version: 2026.1.132.1.15
# Date: 2026-08-27 13:24

# Copyright (C) 2013 - 2026 Efinix Inc. All rights reserved.

enable_remote_update=off
seu_wait_interval=0xffffff
enable_seu_crc_check=off
seu_mode=automatic
