
// Efinity Top-level template
// Version: 2026.1.132.1.15
// Date: 2026-08-27 13:24

// Copyright (C) 2013 - 2026 Efinix Inc. All rights reserved.

// This file may be used as a starting point for Efinity synthesis top-level target.
// The port list here matches what is expected by Efinity constraint files generated
// by the Efinity Interface Designer.

// To use this:
//     #1)  Save this file with a different name to a different directory, where source files are kept.
//              Example: you may wish to save as edge_vision_soc.v
//     #2)  Add the newly saved file into Efinity project as design file
//     #3)  Edit the top level entity in Efinity project to:  edge_vision_soc
//     #4)  Insert design content.


module edge_vision_soc
(
  (* syn_peri_port = 0 *) input i_arstn,
  (* syn_peri_port = 0 *) input sw1,
  (* syn_peri_port = 0 *) input system_uart_0_io_rxd,
  (* syn_peri_port = 0 *) input i_pll_locked,
  (* syn_peri_port = 0 *) input i_mipi_tx_pll_locked,
  (* syn_peri_port = 0 *) input i_hbramClk_pll_locked,
  (* syn_peri_port = 0 *) input i_hbramClk,
  (* syn_peri_port = 0 *) input i_hbramClk_cal,
  (* syn_peri_port = 0 *) input i_hbramClk_fb,
  (* syn_peri_port = 0 *) input i_mipi_clk,
  (* syn_peri_port = 0 *) input i_hbramClk90,
  (* syn_peri_port = 0 *) input i_systemClk,
  (* syn_peri_port = 0 *) input i_fb_clk,
  (* syn_peri_port = 0 *) input i_sysclk_div_2,
  (* syn_peri_port = 0 *) input i_mipi_rx_pclk,
  (* syn_peri_port = 0 *) input i_mipi_tx_pclk,
  (* syn_peri_port = 0 *) input i_mipi_txd_sclk,
  (* syn_peri_port = 0 *) input i_cam_ck_CLKOUT_0,
  (* syn_peri_port = 0 *) input i_mipi_txc_sclk,
  (* syn_peri_port = 0 *) input jtag_inst1_CAPTURE,
  (* syn_peri_port = 0 *) input jtag_inst1_DRCK,
  (* syn_peri_port = 0 *) input jtag_inst1_RESET,
  (* syn_peri_port = 0 *) input jtag_inst1_RUNTEST,
  (* syn_peri_port = 0 *) input jtag_inst1_SEL,
  (* syn_peri_port = 0 *) input jtag_inst1_SHIFT,
  (* syn_peri_port = 0 *) input jtag_inst1_TCK,
  (* syn_peri_port = 0 *) input jtag_inst1_TDI,
  (* syn_peri_port = 0 *) input jtag_inst1_TMS,
  (* syn_peri_port = 0 *) input jtag_inst1_UPDATE,
  (* syn_peri_port = 0 *) input [15:0] hbc_dq_IN_HI,
  (* syn_peri_port = 0 *) input [15:0] hbc_dq_IN_LO,
  (* syn_peri_port = 0 *) input [1:0] hbc_rwds_IN_HI,
  (* syn_peri_port = 0 *) input [1:0] hbc_rwds_IN_LO,
  (* syn_peri_port = 0 *) input mipi_i2c_0_io_scl_read,
  (* syn_peri_port = 0 *) input mipi_i2c_0_io_sda_read,
  (* syn_peri_port = 0 *) input pllin,
  (* syn_peri_port = 0 *) input sw6,
  (* syn_peri_port = 0 *) input sw7,
  (* syn_peri_port = 0 *) input system_spi_0_io_data_0_read,
  (* syn_peri_port = 0 *) input system_spi_0_io_data_1_read,
  (* syn_peri_port = 0 *) input user_dip0,
  (* syn_peri_port = 0 *) input user_dip1,
  (* syn_peri_port = 0 *) input i_cam_d0_FIFO_EMPTY,
  (* syn_peri_port = 0 *) input [7:0] i_cam_d0_HS_IN_0,
  (* syn_peri_port = 0 *) input i_cam_d0_LP_N_IN,
  (* syn_peri_port = 0 *) input i_cam_d0_LP_P_IN,
  (* syn_peri_port = 0 *) input i_cam_d1_FIFO_EMPTY,
  (* syn_peri_port = 0 *) input [7:0] i_cam_d1_HS_IN_0,
  (* syn_peri_port = 0 *) input i_cam_d1_LP_N_IN,
  (* syn_peri_port = 0 *) input i_cam_d1_LP_P_IN,
  (* syn_peri_port = 0 *) input i_cam_ck_LP_N_IN,
  (* syn_peri_port = 0 *) input i_cam_ck_LP_P_IN,
  (* syn_peri_port = 0 *) input mipi_dp_data0_LP_N_IN,
  (* syn_peri_port = 0 *) input mipi_dp_data0_LP_P_IN,
  (* syn_peri_port = 0 *) output o_cam_rstn,
  (* syn_peri_port = 0 *) output o_lcd_rstn,
  (* syn_peri_port = 0 *) output system_uart_0_io_txd,
  (* syn_peri_port = 0 *) output o_pll_rstn,
  (* syn_peri_port = 0 *) output o_mipi_pll_rstn,
  (* syn_peri_port = 0 *) output o_hbramClk_pll_rstn,
  (* syn_peri_port = 0 *) output [2:0] o_hbc_cal_SHIFT,
  (* syn_peri_port = 0 *) output o_hbc_cal_SHIFT_ENA,
  (* syn_peri_port = 0 *) output [4:0] o_hbc_cal_SHIFT_SEL,
  (* syn_peri_port = 0 *) output jtag_inst1_TDO,
  (* syn_peri_port = 0 *) output hbc_cal_pass,
  (* syn_peri_port = 0 *) output hbc_ck_n_HI,
  (* syn_peri_port = 0 *) output hbc_ck_n_LO,
  (* syn_peri_port = 0 *) output hbc_ck_p_HI,
  (* syn_peri_port = 0 *) output hbc_ck_p_LO,
  (* syn_peri_port = 0 *) output hbc_cs_n,
  (* syn_peri_port = 0 *) output [15:0] hbc_dq_OUT_HI,
  (* syn_peri_port = 0 *) output [15:0] hbc_dq_OUT_LO,
  (* syn_peri_port = 0 *) output [15:0] hbc_dq_OE,
  (* syn_peri_port = 0 *) output hbc_rst_n,
  (* syn_peri_port = 0 *) output [1:0] hbc_rwds_OUT_HI,
  (* syn_peri_port = 0 *) output [1:0] hbc_rwds_OUT_LO,
  (* syn_peri_port = 0 *) output [1:0] hbc_rwds_OE,
  (* syn_peri_port = 0 *) output mipi_i2c_0_io_scl_writeEnable,
  (* syn_peri_port = 0 *) output mipi_i2c_0_io_sda_writeEnable,
  (* syn_peri_port = 0 *) output o_led,
  (* syn_peri_port = 0 *) output system_spi_0_io_data_0_write,
  (* syn_peri_port = 0 *) output system_spi_0_io_data_0_writeEnable,
  (* syn_peri_port = 0 *) output system_spi_0_io_data_1_write,
  (* syn_peri_port = 0 *) output system_spi_0_io_data_1_writeEnable,
  (* syn_peri_port = 0 *) output system_spi_0_io_sclk_write,
  (* syn_peri_port = 0 *) output system_spi_0_io_ss,
  (* syn_peri_port = 0 *) output o_cam_d0_FIFO_RD,
  (* syn_peri_port = 0 *) output o_cam_d0_HS_ENA,
  (* syn_peri_port = 0 *) output o_cam_d0_HS_TERM,
  (* syn_peri_port = 0 *) output o_cam_d0_RST,
  (* syn_peri_port = 0 *) output o_cam_d1_FIFO_RD,
  (* syn_peri_port = 0 *) output o_cam_d1_HS_ENA,
  (* syn_peri_port = 0 *) output o_cam_d1_HS_TERM,
  (* syn_peri_port = 0 *) output o_cam_d1_RST,
  (* syn_peri_port = 0 *) output o_cam_ck_HS_ENA,
  (* syn_peri_port = 0 *) output o_cam_ck_HS_TERM,
  (* syn_peri_port = 0 *) output mipi_dp_clk_HS_OE,
  (* syn_peri_port = 0 *) output [7:0] mipi_dp_clk_HS_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_clk_LP_N_OE,
  (* syn_peri_port = 0 *) output mipi_dp_clk_LP_N_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_clk_LP_P_OE,
  (* syn_peri_port = 0 *) output mipi_dp_clk_LP_P_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_clk_RST,
  (* syn_peri_port = 0 *) output mipi_dp_data0_HS_OE,
  (* syn_peri_port = 0 *) output [7:0] mipi_dp_data0_HS_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data0_LP_N_OE,
  (* syn_peri_port = 0 *) output mipi_dp_data0_LP_N_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data0_LP_P_OE,
  (* syn_peri_port = 0 *) output mipi_dp_data0_LP_P_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data0_RST,
  (* syn_peri_port = 0 *) output mipi_dp_data1_HS_OE,
  (* syn_peri_port = 0 *) output [7:0] mipi_dp_data1_HS_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data1_LP_N_OE,
  (* syn_peri_port = 0 *) output mipi_dp_data1_LP_N_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data1_LP_P_OE,
  (* syn_peri_port = 0 *) output mipi_dp_data1_LP_P_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data1_RST,
  (* syn_peri_port = 0 *) output mipi_dp_data2_HS_OE,
  (* syn_peri_port = 0 *) output [7:0] mipi_dp_data2_HS_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data2_LP_N_OE,
  (* syn_peri_port = 0 *) output mipi_dp_data2_LP_N_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data2_LP_P_OE,
  (* syn_peri_port = 0 *) output mipi_dp_data2_LP_P_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data2_RST,
  (* syn_peri_port = 0 *) output mipi_dp_data3_HS_OE,
  (* syn_peri_port = 0 *) output [7:0] mipi_dp_data3_HS_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data3_LP_N_OE,
  (* syn_peri_port = 0 *) output mipi_dp_data3_LP_N_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data3_LP_P_OE,
  (* syn_peri_port = 0 *) output mipi_dp_data3_LP_P_OUT,
  (* syn_peri_port = 0 *) output mipi_dp_data3_RST
);


endmodule

